#!/usr/bin/env bash
# install.sh — put `brain-llm` on your PATH so you can run the agent's CLI from ANY directory.
#
#   ./install.sh            # installs the command `brain-llm`
#   ./install.sh brain      # ...or install it under a different name
#
# It writes a tiny launcher (with this repo's absolute path baked in) into the first writable
# bin dir on your PATH (preferring ~/.local/bin). Re-run after moving the repo.
set -e
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAME="${1:-brain-llm}"

# pick a writable bin dir that is already on PATH
BIN=""
for d in "$HOME/.local/bin" "$HOME/bin"; do
  case ":$PATH:" in *":$d:"*) if [ -d "$d" ] && [ -w "$d" ]; then BIN="$d"; break; fi ;; esac
done
if [ -z "$BIN" ]; then
  BIN="$HOME/.local/bin"; mkdir -p "$BIN"
  echo "note: $BIN was not on your PATH — add this line to ~/.zshrc and restart your shell:"
  echo '      export PATH="$HOME/.local/bin:$PATH"'
fi

TARGET="$BIN/$NAME"
cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# $NAME — global launcher for the brain-llm CLI (generated by install.sh). Runs from any directory;
# the agent's memory is resolved by agent.py (\$BRAIN_HOME, else this repo's agents/, else ~/.brain-llm).
exec env BRAIN_PROG="$NAME" python3 "$REPO/src/agent.py" "\$@"
EOF
chmod +x "$TARGET"

echo "✓ installed: $TARGET"
echo "         →   python3 $REPO/src/agent.py"
echo
echo "try it from anywhere:"
echo "    $NAME --help"
echo "    $NAME home        # shows where the brain lives"
echo "    $NAME wake"
