#!/usr/bin/env bash
# install.sh — put `brain-llm` on your PATH so you can run the agent's CLI from ANY directory.
#
#   ./install.sh            # installs the command `brain-llm`
#   ./install.sh brain      # ...or install it under a different name
#
# It writes a tiny launcher (with this repo's absolute path baked in) into the first writable
# bin dir on your PATH (preferring ~/.local/bin). Re-run after moving the repo.
set -e
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAME="${1:-brain-llm}"

# pick a writable bin dir that is already on PATH
BIN=""
for d in "$HOME/.local/bin" "$HOME/bin"; do
  case ":$PATH:" in *":$d:"*) if [ -d "$d" ] && [ -w "$d" ]; then BIN="$d"; break; fi ;; esac
done
PATH_NOTE=""
if [ -z "$BIN" ]; then
  BIN="$HOME/.local/bin"; mkdir -p "$BIN"
  # $BIN is not on PATH yet — add it to the shell rc so the command actually RESOLVES (idempotent), instead
  # of just printing a note the user has to act on. Picks the right rc by shell; falls back to a printed line.
  RC="$HOME/.zshrc"; case "${SHELL##*/}" in bash) RC="$HOME/.bashrc";; esac
  if grep -qsF '.local/bin' "$RC"; then
    PATH_NOTE="$BIN is already referenced in $RC — open a new terminal (or: source $RC)."
  elif printf '\n# added by brain-llm install.sh — put ~/.local/bin on PATH\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$RC" 2>/dev/null; then
    PATH_NOTE="added $BIN to PATH in $RC — open a NEW terminal, or run:  source $RC"
  else
    PATH_NOTE="$BIN is not on your PATH — add to your shell rc and restart:  export PATH=\"\$HOME/.local/bin:\$PATH\""
  fi
fi

# Provision a project venv with the full deps (PyYAML + wordllama + numpy) so semantic recall is ON BY
# DEFAULT. Best-effort: if python3-venv/pip is missing or the machine is offline, we skip it and the CLI
# still runs on the system python3 with recall degraded to lexical (nothing breaks). The `if` condition is
# allowed to fail under `set -e`, so a failed install never aborts the script.
VENV="$REPO/.venv"
if [ ! -x "$VENV/bin/python" ]; then
  echo "setting up the semantic backend (.venv with wordllama; local & offline, ~134MB one-time)…"
  if python3 -m venv "$VENV" && "$VENV/bin/pip" install -q -r "$REPO/requirements.txt"; then
    echo "✓ semantic recall enabled (wordllama → recall/know by meaning)"
  else
    rm -rf "$VENV"
    echo "note: could not build .venv — the CLI will run on system python3 with LEXICAL recall. To enable"
    echo "      meaning-based recall later:  python3 -m venv .venv && .venv/bin/pip install -r requirements.txt"
  fi
fi

TARGET="$BIN/$NAME"
# Build the launcher with printf + %q so REPO/NAME are shell-escaped: a repo path containing a space,
# quote, backtick or $ produces a correct launcher (an unquoted heredoc baked the raw path in and broke
# - or worse, evaluated - on unusual paths). The format strings are single-quoted, so $BRAIN_HOME / $@
# stay literal in the generated file. The launcher prefers the project venv (semantic ON) over system python3.
{
  printf '#!/usr/bin/env bash\n'
  printf '# %s — global launcher for the brain-llm CLI (generated by install.sh). Runs from any directory;\n' "$NAME"
  printf '# the agent memory is resolved by agent.py ($BRAIN_HOME, else this repo agents/, else ~/.brain-llm).\n'
  printf '# Prefer the project venv (wordllama → semantic recall ON); fall back to system python3.\n'
  printf 'PY=%q/.venv/bin/python; [ -x "$PY" ] || PY=python3\n' "$REPO"
  printf 'exec env BRAIN_PROG=%q "$PY" %q "$@"\n' "$NAME" "$REPO/src/agent.py"
} > "$TARGET"
chmod +x "$TARGET"

echo "✓ installed: $TARGET"
echo "         →   python3 $REPO/src/agent.py"
if [ -n "$PATH_NOTE" ]; then
  echo
  echo "⚠ PATH: $PATH_NOTE"
fi
echo
echo "try it from anywhere (open a new terminal first if PATH was just changed):"
echo "    $NAME --help"
echo "    $NAME home        # shows where the brain lives"
echo "    $NAME wake"
